version: '3.7'

services:
  dm_db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/potgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  dm_web:
    build: .
    command: bash -c "python /usr/src/dm_rest/manage.py migrate --noinput &&
                      python /usr/src/dm_rest/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/dm_rest
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - dm_db
volumes:
  postgres_data:
